In [9]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [10]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [11]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [12]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-1.8626e-09, grad_fn=<MeanBackward0>)

In [13]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [14]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.0513,  0.1471,  1.6113],
        [-1.0767, -0.0613,  0.0873],
        [ 1.9831,  0.8282,  0.1095],
        [-0.3571, -1.3541,  0.2211],
        [-0.9069,  1.5181,  0.6261]], requires_grad=True)

In [15]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.9207, 2.8066],
        [0.0000, 0.5226, 2.4596]])

In [16]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[23.2417],
        [24.2710]])